function create_figure_histogram_weights(X1, YMatrix1, YMatrix2, YMatrix3)
%CREATEFIGURE(X1, YMatrix1, YMatrix2, YMatrix3)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
%  YMATRIX2:  matrix of y data
%  YMATRIX3:  matrix of y data

%  Auto-generated by MATLAB on 23-Mar-2020 15:52:46

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.13 0.709264705882353 0.6184375 0.215735294117647]);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',axes1,'Color',[0 0.447 0.741]);
set(plot1(1),'DisplayName','CS');
set(plot1(2),'DisplayName','MC','LineStyle',':');
set(plot1(3),'DisplayName','IM','LineStyle','-.');

% Set the remaining axes properties
set(axes1,'XTickLabel','');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.349107811339278 0.94468085106383 0.352734377321444 0.0481113475177305],...
    'Orientation','horizontal',...
    'FontSize',14);

% Create axes
axes2 = axes('Parent',figure1,...
    'Position',[0.13 0.409632352941177 0.623125 0.215735294117647]);
hold(axes2,'on');

% Create multiple lines using matrix input to plot
plot2 = plot(X1,YMatrix2,'Parent',axes2,'Color',[0 0.447 0.741]);
set(plot2(2),'LineStyle',':');
set(plot2(3),'LineStyle','-.');

% Set the remaining axes properties
set(axes2,'XTickLabel','');
% Create axes
axes3 = axes('Parent',figure1,...
    'Position',[0.13 0.11 0.6278125 0.215735294117647]);
hold(axes3,'on');

% Create multiple lines using matrix input to plot
plot3 = plot(X1,YMatrix3,'Parent',axes3,'Color',[0 0.447 0.741]);
set(plot3(2),'LineStyle',':');
set(plot3(3),'LineStyle','-.');

% Create xlabel
xlabel('Weights','FontSize',14);

% Create textbox
annotation(figure1,'textbox',[0.812500000000002 0.862765957446809 0 0],...
    'String','Unwt',...
    'FontSize',16,...
    'FitBoxToText','off');

% Create textbox
annotation(figure1,'textbox',[0.781250000000002 0.565602836879433 0 0],...
    'String',{'Var-Covar'},...
    'FontSize',16,...
    'FitBoxToText','off');

% Create textbox
annotation(figure1,'textbox',[0.789062500000002 0.267021276595745 0 0],...
    'String','Entropy',...
    'FontSize',16,...
    'FitBoxToText','off');

